### ISSUE TITLE
netiCRM

### ISSUE THREAD

**Issue by wlc67524** [NETivism/netiCRM-neticrm#2]
請教要如何下載netiCRM

**Comment by junsuwhy** [comment]
您是只要下載程式碼還是要安裝來使用的呢?
如果是下載專案的程式碼，可以在命令字元模式 (Command Line) 用 git 指令
`git clone git@github.com:NETivism/netiCRM.git civicrm`
或是安裝 git 桌面軟體來下載程式碼
https://desktop.github.com/
或是到專案頁直接點專案右上角綠綠的 clone or download 按鈕
https://github.com/NETivism/netiCRM

如果是要安裝使用，可以參考 NetiCRM 的安裝指示
不過過程中需要一些伺服器架設知識
https://github.com/NETivism/netiCRM

**Comment by wlc67524** [comment]
您好我是要安裝使用，可以教我如何安裝嗎？謝謝。
